site_name: Nextcloud VO Federation app
theme:
    name: readthedocs
nav:
    - Home: index.md
    - User guide: user-guide.md
    - Admin guide: admin-guide.md    
    - Developer documentation: development-environment.md
